import {initializeApp} from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js';
import {getAuth,onAuthStateChanged,signInWithEmailAndPassword,signOut} from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js';
import {getFirestore,collection,getDocs,doc,getDoc,onSnapshot} from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js';
const firebaseConfig={apiKey:'AIzaSyAyzAV68m4BRtwmn0iu2vDplZaJ9r_uQVk',authDomain:'rekapinyu.firebaseapp.com',projectId:'rekapinyu',storageBucket:'rekapinyu.firebasestorage.app',messagingSenderId:'835450919713',appId:'1:835450919713:web:818f9f48c5b05330d67c60',measurementId:'G-4KSJC9ENH8'};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);const USERS='rekapinyu_users',DATA='rekapinyu_data';
const $=id=>document.getElementById(id);let users=[],currentUid=null,activityUnsub=null;
function render(view='dashboard'){if(!auth.currentUser)return;$('login').hidden=true;$('content').hidden=false;$('title').textContent={dashboard:'Dashboard',users:'Pengguna',data:'Data Pengguna',activity:'Aktifitas Realtime'}[view];if(view==='dashboard')dashboard();if(view==='users')userList();if(view==='data')dataView();if(view==='activity')activityView()}
async function loadUsers(){const snap=await getDocs(collection(db,USERS));users=snap.docs.map(d=>({id:d.id,...d.data()}));return users}
async function dashboard(){const u=await loadUsers();$('content').innerHTML=`<div class="stats"><div class="stat">Pengguna<b>${u.length}</b></div><div class="stat">Firestore<b>Aktif</b></div><div class="stat">Admin<b>Firebase Auth</b></div><div class="stat">Realtime<b>onSnapshot</b></div></div><div class="card" style="margin-top:14px"><h3>Alur Backend</h3><p>Firebase Authentication → akses admin → Firestore → daftar pengguna → data pengguna → aktifitas realtime.</p><p class="muted">Admin tidak membaca data dari localStorage.</p></div>`}
async function userList(){const u=await loadUsers();$('content').innerHTML='<div class="card"><h3>Pengguna dari rekapinyu_users</h3>'+u.map(x=>`<div class="row"><b>${x.name||'-'}</b><div class="muted">${x.phone||'-'} · UID ${x.id}</div></div>`).join('')+'</div>'}
async function dataView(){const u=await loadUsers();$('content').innerHTML=`<div class="card"><h3>Pilih pengguna</h3><select id="userSelect" style="width:100%;padding:12px;border:1px solid #dbe3eb;border-radius:10px"><option value="">-- pilih --</option>${u.map(x=>`<option value="${x.id}">${x.name||x.phone||x.id}</option>`).join('')}</select><div id="userData" style="margin-top:16px"></div></div>`;$('userSelect').onchange=async e=>{const uid=e.target.value;if(!uid)return;const s=await getDoc(doc(db,DATA,uid));const d=s.exists()?s.data():{};const keys=['InputData','historyData','pengeluaranData','kasbonData','kasirTransactions','LaporanKasir','activityData','LaporanBulanan','backupOtomatisData','receiptSettings'];$('userData').innerHTML='<div class="grid">'+keys.map(k=>`<div class="stat"><b>${Array.isArray(d[k])?d[k].length:(d[k]&&typeof d[k]==='object'?Object.keys(d[k]).length:(d[k]??0))}</b><div>${k}</div></div>`).join('')+'</div>'}}
async function activityView(){const u=await loadUsers();$('content').innerHTML='<div class="card"><h3>Aktifitas Terbaru</h3><div id="activityList">Pilih pengguna...</div><select id="activityUser" style="width:100%;padding:12px;margin:10px 0;border:1px solid #dbe3eb;border-radius:10px"><option value="">-- pilih pengguna --</option>'+u.map(x=>`<option value="${x.id}">${x.name||x.phone||x.id}</option>`).join('')+'</select></div>';const sel=$('activityUser');sel.onchange=()=>{if(activityUnsub)activityUnsub();if(!sel.value)return;activityUnsub=onSnapshot(doc(db,DATA,sel.value),s=>{const a=s.data()?.activityData||[];$('activityList').innerHTML=a.slice().reverse().map(x=>`<div class="row"><b>${x.activity||x.action||x.title||'Aktifitas'}</b><div class="muted">${x.detail||x.description||''} · ${x.date||x.time||x.timestamp||''}</div></div>`).join('')||'<p class="muted">Belum ada aktifitas.</p>'})}}
$('loginBtn').onclick=async()=>{try{await signInWithEmailAndPassword(auth,$('email').value.trim(),$('password').value);$('error').textContent=''}catch(e){$('error').textContent=e.message}};$('logout').onclick=()=>signOut(auth);document.querySelectorAll('aside button[data-view]').forEach(b=>b.onclick=()=>render(b.dataset.view));
onAuthStateChanged(auth,async u=>{if(!u){$('login').hidden=false;$('content').hidden=true;$('status').textContent='Belum login';return}currentUid=u.uid;$('status').textContent=u.email||'Login';render('dashboard')});
